name: Docker Build/Publish Image

on: 
  push:
    branches:
    - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Prepare image name/tag
        id: prep
        run: |
          echo IMAGE_REPO_TAG=$(echo ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:latest | tr '[:upper:]' '[:lower:]' | sed 's/docker-//') >> $GITHUB_ENV
      -
        name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ env.IMAGE_REPO_TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
